TRAIN:
  SOLVER:
    BASE_LR_0: 0.00005
    BASE_LR_0_WARMUP: 0.0000001
    WARMUP_RATIO: 0
    LR_SCALE: 1.5
    LR_ANNEAL: False
    LR_R3: 0.25
  DISTRIBUTED:
    CROSS_DEV_OPS: NcclAllReduce
    NUM_PACKS: 1
  SNAPSHOTS:
    TRAIN_EVAL_PERIOD: inf
    TB_UPDATE_PERIOD: 50
    CKPT_SAVE_PERIOD: 500
  SEED: 0
  BATCH_SIZE: 32
  MAX_STEPS: 35000
  RUN_NAME: 'SF_3D_R3T6_BASE'
  PRETRAIN_CKPT_PATH:
  OUTPUTS_PATH: './outputs/'
TEST:
  BATCH_SIZE: 64
  MAX_THREADS: 0
DATA:
  TRAIN_FEATURES_PATH: './data/youcook2/features_3d_mchunk/training/'
  TEST_FEATURES_PATH: './data/youcook2/features_3d_mchunk/validation/'
  COCO_LABELS_PATH: './data/youcook2/features_3d_mchunk/validation/coco_format_caps.json'
  MAX_FRAMES: 50
  MAX_REGIONS: 9
  MAX_TXT_LENGTH: 50
  BLOCK_LENGTH: 1024
VID_CONFIG:
  D_VID: 2309
TX_CONFIG:
  ENCODER:
    ARCHITECTURE: 'T5'
    D_MODEL: 768
    D_KV: 64
    D_FF: 3072
    NUM_LAYERS: 1
    NUM_HEADS: 12
    ROLE_TYPES: "['attn_relative_role']"
    NUM_RELATIVE_BUCKETS: 32
    MAX_RELATIVE_DISTANCE: 256
    R3_VOCAB_SIZE: 128
    DROPOUT_RATE: 0.1
    EPSILON: 0.000001
    USE_EMBEDDINGS: False
    INITIALIZATION: './data/checkpoints/T5_Pre_Trained/t5-base-tf_model.h5'
  DECODER:
    ARCHITECTURE: 'T5'
    D_MODEL: 768
    D_KV: 64
    D_FF: 3072
    NUM_LAYERS: 12
    NUM_HEADS: 12
    SELF_ROLE_TYPES: "['attn_relative_role']*12"
    CROSS_ROLE_TYPES: "['attn_relative_role']*8 + ['self_role']*4"
    NUM_SELF_RELATIVE_BUCKETS: 32
    MAX_SELF_RELATIVE_DISTANCE: 128
    NUM_CROSS_RELATIVE_BUCKETS: 128
    MAX_CROSS_RELATIVE_DISTANCE: 256
    SELF_R3_VOCAB_SIZE: 128
    CROSS_R3_VOCAB_SIZE: 128
    DROPOUT_RATE: 0.1
    EPSILON: 0.000001
    VOCAB_SIZE: 32128
    INITIALIZATION: './data/checkpoints/T5_Pre_Trained/t5-base-tf_model.h5'
  GENERATION:
    DECODER_START_TOKEN_ID: 0
    PAD_TOKEN_ID: 0
    EOS_TOKEN_ID: 1
    NUM_BEAMS: 1
    EARLY_STOPPING: False
    LENGTH_PENALTY: 1.0
    REPETITION_PENALTY: 1.0
    NO_REPEAT_NGRAM_SIZE: 0
    USE_CACHE: False